layout: {zmk_keyboard: base}
layers:
  BASE LAYER:
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: A, h: '$$mdi:apple-keyboard-shift$$'}
  - {t: S, h: '$$mdi:apple-keyboard-option$$'}
  - {t: D, h: '$$mdi:apple-keyboard-control$$'}
  - {t: F, h: '$$mdi:apple-keyboard-command$$'}
  - G
  - H
  - {t: J, h: '$$mdi:apple-keyboard-command$$'}
  - {t: K, h: '$$mdi:apple-keyboard-control$$'}
  - {t: L, h: '$$mdi:apple-keyboard-option$$'}
  - {t: ;, h: '$$mdi:apple-keyboard-shift$$'}
  - Z
  - X
  - {t: C, h: NUM}
  - V
  - B
  - N
  - M
  - {t: ',', s: ;}
  - {t: ., s: ':'}
  - /
  - $$mdi:apple-keyboard-control$$
  - {t: '$$mdi:backspace-outline$$', h: NUM}
  - {t: '$$mdi:keyboard-space$$', h: SYM_R, s: $$dot_spc$$}
  - {t: '$$mdi:keyboard-return$$', h: SYM_L}
  - $$mdi:keyboard-space$$
  - $$mdi:apple-keyboard-control$$
  APTMAK_W:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: R, h: '$$mdi:apple-keyboard-command$$'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: H, h: '$$mdi:apple-keyboard-control$$'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: N, h: '$$mdi:apple-keyboard-control$$'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: O, h: '$$mdi:apple-keyboard-command$$'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  NUM:
  - F12
  - F7
  - F8
  - F9
  - {type: none}
  - '}'
  - '7'
  - '8'
  - '9'
  - {type: none}
  - F10
  - F4
  - F5
  - F6
  - {type: none}
  - '{'
  - '4'
  - '5'
  - '6'
  - E
  - {type: none}
  - F1
  - {t: F2, type: held}
  - F3
  - {type: none}
  - {type: none}
  - '1'
  - '2'
  - '3'
  - {type: none}
  - {type: none}
  - {t: ',', type: held alternate}
  - {t: ▽, type: trans}
  - {t: '0', h: SYM_L}
  - .
  - {type: none}
  NAV:
  - {type: none}
  - {type: none}
  - $$tabler:square-x$$
  - $$tabler:browser-x$$
  - {type: none}
  - $$mdi:monitor-screenshot$$
  - $$pg_dn$$
  - $$mdi:arrow-up-bold$$
  - $$pg_up$$
  - $$mdi:arrow-right-bold$$
  - {t: '$$mdi:apple-keyboard-shift$$', h: '$$tabler:sticker$$'}
  - {t: '$$mdi:apple-keyboard-option$$', h: '$$tabler:sticker$$'}
  - {t: '$$mdi:apple-keyboard-control$$', h: '$$tabler:sticker$$'}
  - {t: '$$mdi:apple-keyboard-command$$', h: '$$tabler:sticker$$'}
  - {type: none}
  - $$mdi:arrow-left-bold$$
  - $$mdi:arrow-down-bold$$
  - $$mdi:arrow-up-bold$$
  - $$mdi:arrow-right-bold$$
  - $$mdi:power-sleep$$
  - {type: none}
  - {t: '$$mdi:swap-horizontal$$', h: Windows}
  - {type: none}
  - {t: '$$mdi:swap-horizontal$$', h: Tabs}
  - {type: none}
  - {type: none}
  - $$screen-prev$$
  - $$tabler:mouse$$
  - $$tabler:screen-share$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: none}
  - {type: none}
  NAV_W:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Alt+F4
  - Ctl+W
  - {t: ▽, type: trans}
  - Gui+Sft+S
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '$$mdi:apple-keyboard-command$$', h: '$$tabler:sticker$$'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '$$mdi:apple-keyboard-control$$', h: '$$tabler:sticker$$'}
  - {t: ▽, type: trans}
  - Ctl+$$mdi:backspace-reverse-outline$$
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - $$mdi:power-sleep$$
  - {t: ▽, type: trans}
  - '&swapper_win'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Gui+Ctl+$$mdi:arrow-left-bold$$
  - {t: ▽, type: trans}
  - Gui+Ctl+$$mdi:arrow-right-bold$$
  - {t: ▽, type: trans}
  - {type: none}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: none}
  SYM_L:
  - '!'
  - '@'
  - '#'
  - '&'
  - '%'
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - $$escape$$
  - '`'
  - \
  - '|'
  - '~'
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {t: '`', h: '$$tabler:sticker$$'}
  - {t: ´, h: '$$tabler:sticker$$', type: held alternate}
  - <
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: held alternate}
  - {t: ▽, type: trans}
  - {type: held}
  - {type: none}
  - {type: none}
  SYM_R:
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - ^
  - +
  - '*'
  - $/€/°
  - ''''
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - _
  - '-'
  - /
  - '='
  - '!'
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - '>'
  - ;
  - ':'
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: held}
  - {t: ▽, type: trans}
  - {type: none}
  - {type: none}
  SYM_RW:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&curr_deg_win'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  ADJ:
  - A
  - {type: none}
  - $$mdi:microsoft-windows$$
  - $$mdi:apple$$
  - $$mdi:progress-download$$
  - $$mdi:progress-download$$
  - $$mdi:play-pause$$
  - $$mdi:skip-next$$
  - $$mdi:skip-previous$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - $$mdi:backup-restore$$
  - $$mdi:backup-restore$$
  - $$mdi:volume-low$$
  - $$mdi:volume-high$$
  - $$mdi:volume-off$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: held}
  - {type: none}
  - {type: none}
  - {type: none}
  - $$mdi:brightness-7$$
  - $$mdi:brightness-5$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: held}
  - {type: held}
  - {type: held}
  - {type: none}
  - {type: none}
  LOCK:
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
combos:
- p: [11, 12]
  k: $$escape$$
  l: [BASE LAYER, APTMAK_W]
- p: [12, 13]
  k: $$mdi:keyboard-tab$$
  l: [BASE LAYER, APTMAK_W]
- p: [21, 22]
  k: $$mdi:content-copy$$
  l: [BASE LAYER]
- p: [22, 23]
  k: $$mdi:content-paste$$
  l: [BASE LAYER]
- p: [21, 22, 23]
  k: $$mdi:content-cut$$
  l: [BASE LAYER]
  a: bottom
- p: [10, 11]
  k: $$mdi:undo$$
  l: [BASE LAYER]
- p: [13, 14]
  k: $$mdi:redo$$
  l: [BASE LAYER]
- p: [21, 22]
  k: $$mdi:content-copy$$
  l: [APTMAK_W]
- p: [22, 23]
  k: $$mdi:content-paste$$
  l: [APTMAK_W]
- p: [21, 22, 23]
  k: $$mdi:content-cut$$
  l: [APTMAK_W]
- p: [10, 11]
  k: $$mdi:undo$$
  l: [APTMAK_W]
- p: [13, 14]
  k: $$mdi:redo$$
  l: [APTMAK_W]
- p: [16, 17]
  k: (
  l: [BASE LAYER, APTMAK_W, SYM_R, SYM_RW, NUM]
- p: [17, 18]
  k: )
  l: [BASE LAYER, APTMAK_W, SYM_R, SYM_RW, NUM]
- p: [26, 27]
  k: {h: '[', s: '{'}
  l: [BASE LAYER, APTMAK_W, SYM_R, SYM_RW, NUM]
- p: [27, 28]
  k: {h: ']', s: '}'}
  l: [BASE LAYER, APTMAK_W, SYM_R, SYM_RW, NUM]
- p: [6, 7]
  k: $$mdi:backspace-outline$$
  l: [BASE LAYER, APTMAK_W, NAV, NAV_W, NUM]
- p: [7, 8]
  k: $$mdi:backspace-reverse-outline$$
  l: [BASE LAYER, APTMAK_W, NAV, NAV_W, NUM]
- p: [6, 7, 8]
  k: {h: WORD, s: '$$mdi:backspace-outline$$'}
  l: [BASE LAYER]
  a: top
- p: [6, 7, 8]
  k: {h: LINE, s: '$$mdi:backspace-outline$$'}
  l: [NAV]
  a: top
- p: [6, 7, 8]
  k: Ctl+$$mdi:backspace-outline$$
  l: [APTMAK_W]
- p: [6, 7, 8]
  k: '&del_line_win'
  l: [NAV_W]
- p: [0, 9, 32, 33]
  k: $$mdi:lock-open-outline$$
  l: [BASE LAYER]
  a: bottom
  o: 0.3
  arc_scale: 1.05
